apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dummy-portal
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/apps/dummy-portal/kustomize
  prune: true
  timeout: 5m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
