apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-ingress-gateway
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/infra/cilium-ingress-gateway/kustomize
  prune: true
  timeout: 5m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
