all:
  hosts:
    test-vm-1:
      ansible_host: 192.168.178.211
    test-vm-2:
      ansible_host: 192.168.178.212
    test-vm-3:
      ansible_host: 192.168.178.213
  vars:
    ansible_user: ansible

test:
  hosts:
    test-vm-1:
    test-vm-2:
    test-vm-3:

docker:
  hosts:
    test-vm-1: