apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-namespace
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/infra/external-dns/namespace
  prune: true
  timeout: 5m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: external-dns-namespace
  interval: 10m
  path: ./flux/infra/external-dns/secrets
  prune: true
  timeout: 5m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: external-dns-secrets
  interval: 10m
  path: ./flux/infra/external-dns/kustomize
  prune: true
  timeout: 5m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
