services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "${PIHOLE_IP}:53:53/tcp"
      - "${PIHOLE_IP}:53:53/udp"
      - "${PIHOLE_HTTP_PORT}:80/tcp"
      - "${PIHOLE_HTTPS_PORT}:443/tcp"
    environment:
      TZ: 'Etc/UTC'
      FTLCONF_dns_listeningMode: 'all'
      WEBPASSWORD_FILE: webpassword
    volumes:
      - data:/etc/pihole
    secrets:
      - webpassword
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE

volumes:
  data: {}

secrets:
  webpassword:
    file: ./webpassword.txt