services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "${PIHOLE_IP}:53:53/tcp"
      - "${PIHOLE_IP}:53:53/udp"
      - "${PIHOLE_HTTP_PORT}:80/tcp"
      - "${PIHOLE_HTTPS_PORT}:443/tcp"
    environment:
      TZ: 'Etc/UTC'
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_webserver_api_password: 'qwerty'
      PIHOLE_UID: "${PIHOLE_UID}"
      PIHOLE_GID: "${PIHOLE_GID}"
    volumes:
      - ./etc-pihole:/etc/pihole