---
- name: runc
  block:
    - name: runc | install
      ansible.builtin.get_url:
        url: "https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64"
        dest: /usr/local/sbin/runc
        checksum: "{{ runc_checksum }}"
        mode: '0755'
        owner: root
        group: root
