---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-gateway

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public
  namespace: cilium-gateway
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 192.168.178.211
  listeners:
    - name: http-k8s-home-arpa
      hostname: "*.k8s.home.arpa"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    # - name: http-xxx-com
    #   hostname: xxx.com
    #   port: 80
    #   protocol: HTTP
    #   allowedRoutes:
    #     namespaces:
    #       from: All
    # - name: http-yyy-net
    #   hostname: yyy.net
    #   port: 80
    #   protocol: HTTP
    #   allowedRoutes:
    #     namespaces:
    #       from: All