---
- name: k8s
  block:
    - name: k8s | check if node already joined
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: k8s | join worker node
      when: not kubelet_conf.stat.exists
      block:
        - name: k8s | get join command
          ansible.builtin.command: kubeadm token create --print-join-command
          delegate_to: "{{ groups['k8s_node_control'] | first }}"
          run_once: true
          register: join_command

        - name: k8s | join node to cluster
          ansible.builtin.command: "{{ join_command.stdout }}"

        - name: k8s | label node
          ansible.builtin.command: >
            kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker= --overwrite
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf
          delegate_to: "{{ groups['k8s_node_control'] | first }}"
