services:
  ansible:
    build: .
    container_name: ansible
    image: ansible
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - ./workspace:/ansible
    working_dir: /ansible
    entrypoint: ["/bin/sh", "-c"]
    command: ["tail -f /dev/null"]