test:
  hosts:
    test_vm_1:
      ansible_host: 192.168.178.211
    test_vm_2:
      ansible_host: 192.168.178.212
    test_vm_3:
      ansible_host: 192.168.178.213
  vars:
    ansible_user: dms