---
- name: gateway api
  block:
    - name: gateway api | install CRDs
      ansible.builtin.command: >
        kubectl apply
          --server-side
          -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v{{ gateway_api_version }}/standard-install.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: gateway_api_apply
      changed_when: false
      retries: 30
      delay: 5
      until: gateway_api_apply.rc == 0