apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-web-ui-policies
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infra/flux-web-ui/policies
  prune: true
  wait: true
  timeout: 2m
  dependsOn:
    - name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-web-ui-ingress
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infra/flux-web-ui/ingress
  prune: true
  wait: true
  timeout: 2m
  dependsOn:
    - name: flux-system
