apiVersion: v1
kind: Service
metadata:
  name: dummy-portal
  namespace: dummy-portal
spec:
  selector:
    app: dummy-portal
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
